### ISSUE TITLE
Add messaging on lead notification emails for requests that stay one-to-one (Specific Supplier), communicating to the profile that they're the only vendor getting the lead.

### ISSUE THREAD

**Issue by jmpoko** [ProHUB/Changes#4]
**Is your feature request related to a problem? Please describe.**
Suppliers don't know they are the only one to receive the lead

**Describe the solution you'd like**
Add a label next to the lead in "[Leads I'm Matched To](https://www.productionhub.com/leads)" section in MY ACCOUNT

Technical solutions / new messaging for requests that stay one-to-one / "Specific Supplier"

(1) develop some admin tools / best practices for "Specific Supplier" requests and 
(2) add new messaging on lead notification emails and text messages that go to profiles who receive an exclusive / one-to-one request letting them know the lead is only going to them and they need to respond to the buyer or let us know they're not available/interested so we can help the buyer find someone else.
(3) add label to the 1:1 lead in the user’s  [’Leads I’m Matched To’ section of MY ACCOUNT](https://www.productionhub.com/leads) or create a separate section just for these in MY ACCOUNT

 
Proposed changes / process:

Option 1: Add a step / checkbox:
From the admin 'Edit Request' page:
https://www.productionhub.com/admin/requestengine/edit/ ... 
 
in the Suppliers' section/page:
https://www.productionhub.com/admin/requestengine/suppliers/ ...
- Add a Checkbox to the left of the 'Send Supplier Notifications' button that IF checked triggers an additional message to the lead notification email and/or text message (or a new/different lead notification email/text).

- or -                      
Option 2: 
If a request's Target is still set to Specific Supplier when admin sends the lead notification email out, then that triggers a special lead notification email/text message. Need to dummy-proof this. If a request that comes in through a specific profile does not stay one-to-one, the best practice would be (and should already be) to change the Target from 'Specific Supplier' to "Within Radius of City" or "Everywhere" / "Country Only", etc.
The profile that the request came in through would still be documented in the notes as soon as the lead is submitted to us, correct?

Add new copy to the email and text notifications that go out to profiles who receive a one-to-one request and/or create a new/separate email/text notification for one-to-one requests:

TEXT notification copy:
ATTENTION: This is an exclusive lead, currently only matched to you.

EMAIL notification copy:
ATTENTION: This is an exclusive lead, currently only matched to you.
The client submitted their request through your profile and is specifically interested in you/your company for their project.
Please keep this project within the ProductionHUB network. If you are unavailable for this project, please let us know so we can assist the client with hiring another vendor through ProductionHUB.

MY ACCOUNT:
- Add a call out / label to one-to-one leads in the Leads I'm Matched To section of MY ACCOUNT:  https://www.productionhub.com/leads

"EXCLUSIVE LEAD" (with helper text?)

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Please include a link if appropriate.

**Comment by malevolence** [comment]
This is all fairly do-able but I don't think we should over-complicate it. There are already mechanisms in place for signifying that a request is for a specific supplier. We just need employees to understand that and act accordingly. Some messaging when trying to match suppliers to requests that are configured as one-to-one should make it easier.

### Employees view when trying to match suppliers on a one-to-one request
![admin-one-to-one](https://github.com/ProHUB/Changes/assets/392048/8738851d-3b07-4266-bd48-e514c3239004)

The messaging to suppliers is easy enough to add and I have included some mockups below. This would show when the targeting of the request is set to Supplier Only and the SupplierID on the request is the same as the supplier viewing the request. This should prevent any incorrect messaging.

For the email notifications, we can just use the current one and add some verbiage when it is one-to-one, along with a link to let them indicate if they are unavailable / uninterested. The SMS messaging should be kept as short as possible due to message length constraints. With the example verbiage, it would exceed the recommended maximum length for many requests.

### Suppliers view of leads in My Account
![supplier-one-to-one-01](https://github.com/ProHUB/Changes/assets/392048/f01b3fbc-953a-4c15-a85b-0578ab939175)
![supplier-one-to-one-02](https://github.com/ProHUB/Changes/assets/392048/9b5f7ed8-6a98-4538-853f-a581d28c4c73)
![supplier-one-to-one-03](https://github.com/ProHUB/Changes/assets/392048/8e6692d8-1bd2-403a-a238-688142c80558)

**Comment by malevolence** [comment]
What additional information would we want to collect (if any) when a supplier indicates that they can't service a particular one-to-one request? This would be included in the email back to us and included in the note on the request.
